### ISSUE TITLE
ES6 Classes, extend Store/Actions.

### ISSUE THREAD

**Issue by Serfenia** [christianalfoni/flux-react#5]
Hey Christian,

Would it be possible to create stores and actions through a class extension? React supports ES6 classes since release 0.13.0, and currently I am creating their components like this:

```
class SomeComponent extends React.Component {
  ...
}

export default SomeComponent;
```

I also import them through the new module system (`import SomeComponent from './SomeComponent.js';`). Then I use [BabelJS](https://babeljs.io/) to convert ES6 syntax to ES5 for now until browsers fully support it.

Would it possible to do this for your stores and actions as well? Something Like:

```
// Store
import Flux from 'flux-react';

class SomeStore extends Flux.Store {
  constructor() {
     this.actions = [
       ..
     ]
     ...
  }
}

export default SomeStore; // this already works
```

```
// Actions
import Flux from 'flux-react';

class Dispatcher extends Flux.Actions { 
  // Not sure how you would implement it here.
}

export default Dispatcher; // this already works
```

Regards,
Patrick

**Comment by christianalfoni** [comment]
Hi @Serfenia and sorry for a late reply. I have been sick with the flue and I am moving across the country with my girlfriend, so has been difficult following up on stuff.

Its definitely possible to make this more ES2015 friendly, though I think it needs some thought. I can not see much benefit in regards of syntax. And you do not really need inheritance. It kinda feels like pushing a square block down a circle shaped hole ;-)

That said, if you have more ideas on this, please pass them this way. I will keep it some more thought on my end!

**Comment by Serfenia** [comment]
Hey @christianalfoni, no problem!

I get your point. The idea came up through the way React defines her components. A component was previously created through `createClass`. 

The same happens with your flux implementation for stores for example. A store can implement some private (module pattern) and public (facade pattern) functionalities. Also it is possible to define your own methods. It feels a lot like implementing React components, the only difference is the private/public API of the stores that is currently available through flux-react. 

I would be interest in your throughts of it.

**Comment by christianalfoni** [comment]
Hi @Serfenia and sorry for late reply, still fighting off this freakin flue.

As I understand it the `createClass` method is not going away. At least not until JavaScript has natively solved a concept of "mixins". There is a lot of debate on ES classes, as it brings with it a pattern that does not recognize the strength of JavaScript. JavaScript allows for composing objects, which is better than having a long inheritance chain. Anyways, that is a different discussion :-)

So my thoughts on this subject is really to not rush into ES classes because the syntax looks nice, there has to be some value to it. Either it being easier to understand or "inheritance" makes sense.

You have to excuse my negative view on ES classes ;-) Its really great with the code examples you suggested. If you have some ideas on giving a more detailed implementation suggestion I would love to see that :-)
